name: Train pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install dvc

    - name: Rebuild raw_data.csv using DVC (dvc update)
      run: |
        dvc update data/raw/raw_data.csv.dvc

    - name: Run dataset step
      run: python itu_sdse_project/dataset.py

    - name: Run features step
      run: python itu_sdse_project/features.py

    - name: Run training step
      run: python itu_sdse_project/modeling/train.py

    - name: Upload Model Artifact
      uses: actions/upload-artifact@v4.4.0
      with:
        name: model
        path: model/model.pkl