name: Model training and validation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Run pipeline with dagger
        uses: dagger/dagger-for-github@v8.2.0
        with:
          version: "latest"
          workdir: go
          verb: run
          args: go run .

      - name: Upload model (.pkl) artifact
        uses: actions/upload-artifact@v4
        with:
          name: model
          path: model/model.pkl

  validate:
    runs-on: ubuntu-latest
    needs: train

    steps:
      - name: Download model (.pkl) artifact
        uses: actions/download-artifact@v4
        with:
          name: model
          path: model

      - name: Validate model 
        uses: lasselundstenjensen/itu-sdse-project-model-validator@main